services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: scophee/vprofiledb
    container_name: vprodb
    ports:
      - '3306:3306'
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=accounts

  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - '11211:11211'

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp01:
    build:
      context: ./Docker-files/app
    image: scophee/vprofileapp
    container_name: vproapp01
    ports:
      - '8080:8080'
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb01:
    build:
      context: ./Docker-files/web
    image: scophee/vprofileweb
    container_name: vproweb
    ports:
      - '80:80'

volumes:
  vprodbdata: {}
  vproappdata: {}
